# Generated by Django 5.0.6 on 2024-10-15 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('color', 'Color'), ('cantidad', 'Cantidad'), ('tamaño', 'Tamaño'), ('peso', 'Peso'), ('vencimiento', 'Vencimiento'), ('origen', 'Origen'), ('otros', 'Otros')], max_length=25)),
                ('descripcion', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('frutas verduras', 'Frutas y verduras'), ('carnes pescados', 'Carnes y pescados'), ('lacteos huevos', 'Lácteos y huevos'), ('panaderia reposteria', 'Panadería y repostería'), ('cereales granos', 'Cereales y granos'), ('bebidas', 'Bebidas'), ('alimentos congelados', 'Alimentos congelados'), ('snacks botanas', 'Snacks y botanas'), ('comidas preparadas', 'Comidas preparadas'), ('salsas condimentos y especias', 'Salsas, condimentos y especias'), ('conservas', 'Alimentos enlatados y conservas'), ('productos organicos', 'Productos orgánicos'), ('alimentos sin gluten', 'Alimentos sin gluten'), ('dulces chocolates', 'Dulces y chocolates'), ('aceites grasas', 'Aceites y grasas'), ('pasta arroces', 'Pasta y arroces'), ('legumbres', 'Legumbres')], max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=7, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.CharField(max_length=10)),
                ('caracteristicas', models.ManyToManyField(to='inicio.caracteristica')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inicio.categoria')),
            ],
        ),
    ]
