# Generated by Django 4.2.16 on 2024-10-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('TEC', 'Tecnologia'), ('ALM', 'Alimentos'), ('HOG', 'Hogar')], max_length=20),
        ),
    ]
