# Generated by Django 4.2.16 on 2024-10-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caracteristicas',
            new_name='Caracteristica',
        ),
    ]
