# Generated by Django 5.0.6 on 2024-10-15 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alter_categoria_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='Marca Generica', max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='caracteristica',
            name='nombre',
            field=models.CharField(choices=[('Color', 'Color'), ('Cantidad', 'Cantidad'), ('Tamaño', 'Tamaño'), ('Peso', 'Peso'), ('Vencimiento', 'Vencimiento'), ('Origen', 'Origen'), ('Otros', 'Otros')], max_length=25),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inicio.marca'),
        ),
    ]
