# Generated by Django 4.2.16 on 2024-10-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_rename_caracteristicas_caracteristica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='caracteristicas',
            field=models.ManyToManyField(default='', null=True, to='inicio.caracteristica'),
        ),
    ]
