# Generated by Django 5.0.6 on 2024-10-15 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default='Marca Generica', on_delete=django.db.models.deletion.CASCADE, to='inicio.marca'),
        ),
    ]
