# Generated by Django 4.2.16 on 2024-10-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_productos_caracteristicas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('Tecnologia', 'Tecnologia'), ('Alimentos', 'Alimentos'), ('hogar', 'Hogar')], max_length=20),
        ),
    ]
