# Generated by Django 5.0.6 on 2024-10-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_marca_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
    ]
