# Generated by Django 5.0.6 on 2024-10-15 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_remove_producto_marca'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Marca',
        ),
    ]
