# Generated by Django 4.2.16 on 2024-10-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='caracteristicas',
            field=models.ManyToManyField(to='inicio.caracteristica'),
        ),
    ]
