# Generated by Django 5.0.6 on 2024-10-16 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0009_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, to='inicio.marca'),
        ),
    ]
