# Generated by Django 5.0.6 on 2024-10-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_producto_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caracteristicas',
            field=models.ManyToManyField(max_length=50, to='inicio.caracteristica'),
        ),
    ]
